package netcode

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

// Wire compatibility tests against golden vectors generated by the C
// reference implementation (see testdata/generate_vectors.c). Every vector is
// checked in both directions:
//
//  1. read: this implementation must decode (and where applicable decrypt)
//     the C-generated bytes back to the expected fields, and
//  2. write: this implementation must encode the same fields to the exact
//     same bytes the C implementation produced.
//
// Together these prove the two implementations are byte compatible on the
// wire. The CI wire-compat job additionally regenerates the vectors from the
// C implementation's main branch and fails if they differ from the committed
// ones, so drift on either side is caught on every pull request.

// fixed fixture values. these are mirrored in testdata/generate_vectors.c and must not change.

const (
	fixtureProtocolID        = 0x1122334455667788
	fixtureClientID          = 0x0102030405060708
	fixtureTimeoutSeconds    = 15
	fixtureCreateTimestamp   = 0xAABBCCDD11223300
	fixtureExpireTimestamp   = 0xAABBCCDD11223344
	fixtureChallengeSequence = 0xFFEEDDCCBBAA9988
)

func fixturePattern(data []byte, multiplier int, offset int) {
	for i := range data {
		data[i] = uint8(i*multiplier + offset)
	}
}

func fixtureKey(multiplier int, offset int) []byte {
	key := make([]byte, KeyBytes)
	fixturePattern(key, multiplier, offset)
	return key
}

func fixturePacketKey() []byte      { return fixtureKey(7, 1) }
func fixturePrivateKey() []byte     { return fixtureKey(11, 3) }
func fixtureChallengeKey() []byte   { return fixtureKey(13, 5) }
func fixtureC2SKey() [KeyBytes]byte { return [KeyBytes]byte(fixtureKey(3, 1)) }
func fixtureS2CKey() [KeyBytes]byte { return [KeyBytes]byte(fixtureKey(5, 2)) }

func fixtureConnectTokenNonce() [connectTokenNonceBytes]byte {
	var nonce [connectTokenNonceBytes]byte
	fixturePattern(nonce[:], 17, 9)
	return nonce
}

func fixtureServerAddresses() [3]Address {
	return [3]Address{
		{Type: AddressIPv4, IPv4: [4]byte{127, 0, 0, 1}, Port: 40000},
		{Type: AddressIPv6, IPv6: [8]uint16{0xfe80, 0, 0, 0, 0x0202, 0xb3ff, 0xfe1e, 0x8329}, Port: 50000},
		{Type: AddressIPv4, IPv4: [4]byte{10, 24, 93, 7}, Port: 12345},
	}
}

func fixtureConnectTokenPrivate() *connectTokenPrivate {
	token := &connectTokenPrivate{
		clientID:           fixtureClientID,
		timeoutSeconds:     fixtureTimeoutSeconds,
		numServerAddresses: 3,
		clientToServerKey:  fixtureC2SKey(),
		serverToClientKey:  fixtureS2CKey(),
	}
	addresses := fixtureServerAddresses()
	copy(token.serverAddresses[:], addresses[:])
	fixturePattern(token.userData[:], 7, 13)
	return token
}

func loadVector(t *testing.T, name string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("failed to load wire vector: %v (regenerate with testdata/generate_vectors.c)", err)
	}
	return data
}

func TestWireCompatConnectTokenPrivate(t *testing.T) {
	plaintextVector := loadVector(t, "connect_token_private.bin")
	encryptedVector := loadVector(t, "connect_token_private_encrypted.bin")

	// writing the fixture private connect token must produce the C bytes

	expectedToken := fixtureConnectTokenPrivate()

	var written [connectTokenPrivateBytes]byte
	expectedToken.write(written[:])
	check(t, bytes.Equal(written[:], plaintextVector))

	// encrypting it must produce the C ciphertext (XChaCha20-Poly1305 is
	// deterministic given the same key and nonce)

	nonce := fixtureConnectTokenNonce()

	encrypted := written
	check(t, encryptConnectTokenPrivate(encrypted[:], fixtureProtocolID, fixtureExpireTimestamp, nonce[:], fixturePrivateKey()) == nil)
	check(t, bytes.Equal(encrypted[:], encryptedVector))

	// the C ciphertext must decrypt and read back to the same fields

	decrypted := [connectTokenPrivateBytes]byte(encryptedVector)
	check(t, decryptConnectTokenPrivate(decrypted[:], fixtureProtocolID, fixtureExpireTimestamp, nonce[:], fixturePrivateKey()) == nil)
	check(t, bytes.Equal(decrypted[:connectTokenPrivateBytes-MacBytes], plaintextVector[:connectTokenPrivateBytes-MacBytes]))

	var readToken connectTokenPrivate
	check(t, readToken.read(decrypted[:]) == nil)
	check(t, readToken == *expectedToken)
}

func TestWireCompatConnectToken(t *testing.T) {
	tokenVector := loadVector(t, "connect_token.bin")
	encryptedPrivateVector := loadVector(t, "connect_token_private_encrypted.bin")

	// reading the C public connect token must give the fixture fields

	var readToken connectToken
	check(t, readToken.read(tokenVector) == nil)

	check(t, readToken.protocolID == fixtureProtocolID)
	check(t, readToken.createTimestamp == fixtureCreateTimestamp)
	check(t, readToken.expireTimestamp == fixtureExpireTimestamp)
	check(t, readToken.nonce == fixtureConnectTokenNonce())
	check(t, bytes.Equal(readToken.privateData[:], encryptedPrivateVector))
	check(t, readToken.timeoutSeconds == fixtureTimeoutSeconds)
	check(t, readToken.numServerAddresses == 3)
	addresses := fixtureServerAddresses()
	for i := range addresses {
		check(t, readToken.serverAddresses[i].Equal(addresses[i]))
	}
	check(t, readToken.clientToServerKey == fixtureC2SKey())
	check(t, readToken.serverToClientKey == fixtureS2CKey())

	// writing the same fields must produce the C bytes

	var written [ConnectTokenBytes]byte
	readToken.write(written[:])
	check(t, bytes.Equal(written[:], tokenVector))
}

func TestWireCompatChallengeToken(t *testing.T) {
	plaintextVector := loadVector(t, "challenge_token.bin")
	encryptedVector := loadVector(t, "challenge_token_encrypted.bin")

	// writing the fixture challenge token must produce the C bytes

	expectedToken := challengeToken{clientID: fixtureClientID}
	fixturePattern(expectedToken.userData[:], 9, 17)

	var written [challengeTokenBytes]byte
	expectedToken.write(written[:])
	check(t, bytes.Equal(written[:], plaintextVector))

	// encrypting it must produce the C ciphertext

	encrypted := written
	check(t, encryptChallengeToken(encrypted[:], fixtureChallengeSequence, fixtureChallengeKey()) == nil)
	check(t, bytes.Equal(encrypted[:], encryptedVector))

	// the C ciphertext must decrypt and read back to the same fields

	decrypted := [challengeTokenBytes]byte(encryptedVector)
	check(t, decryptChallengeToken(decrypted[:], fixtureChallengeSequence, fixtureChallengeKey()) == nil)
	check(t, bytes.Equal(decrypted[:challengeTokenBytes-MacBytes], plaintextVector[:challengeTokenBytes-MacBytes]))

	var readToken challengeToken
	check(t, readToken.read(decrypted[:]) == nil)
	check(t, readToken == expectedToken)
}

// readWireCompatPacket reads a packet vector with the fixture keys.
func readWireCompatPacket(t *testing.T, vector []byte, expectedSequence uint64) packet {
	t.Helper()

	// readPacket decrypts in place, so work on a copy
	buffer := append([]byte(nil), vector...)

	allowedPackets := allPacketsAllowed()

	var sequence uint64
	p := readPacket(buffer, &sequence, fixturePacketKey(), fixtureProtocolID, 0, fixturePrivateKey(), &allowedPackets, nil)
	if p == nil {
		t.Fatal("failed to read C-generated packet")
	}
	check(t, sequence == expectedSequence)
	return p
}

// writeWireCompatPacket writes a packet with the fixture keys and asserts it
// matches the C-generated vector byte for byte.
func writeWireCompatPacket(t *testing.T, p packet, sequence uint64, vector []byte) {
	t.Helper()

	var buffer [maxPacketBytes]byte
	packetBytes := writePacket(p, buffer[:], sequence, fixturePacketKey(), fixtureProtocolID)
	check(t, packetBytes == len(vector))
	check(t, bytes.Equal(buffer[:packetBytes], vector))
}

func TestWireCompatConnectionRequestPacket(t *testing.T) {
	vector := loadVector(t, "packet_connection_request.bin")
	encryptedPrivateVector := loadVector(t, "connect_token_private_encrypted.bin")
	plaintextPrivateVector := loadVector(t, "connect_token_private.bin")

	// writing the request packet must produce the C bytes (this packet type is
	// not encrypted at the packet level, it carries the already encrypted
	// private connect token)

	inputPacket := &connectionRequest{
		versionInfo:                 versionInfo,
		protocolID:                  fixtureProtocolID,
		connectTokenExpireTimestamp: fixtureExpireTimestamp,
		connectTokenNonce:           fixtureConnectTokenNonce(),
		connectTokenData:            [connectTokenPrivateBytes]byte(encryptedPrivateVector),
	}
	writeWireCompatPacket(t, inputPacket, 0, vector)

	// reading the C bytes must decrypt the private connect token and give back
	// the fixture fields

	outputPacket, ok := readWireCompatPacket(t, vector, 0).(*connectionRequest)
	check(t, ok)
	check(t, outputPacket.versionInfo == versionInfo)
	check(t, outputPacket.protocolID == fixtureProtocolID)
	check(t, outputPacket.connectTokenExpireTimestamp == fixtureExpireTimestamp)
	check(t, outputPacket.connectTokenNonce == fixtureConnectTokenNonce())
	check(t, bytes.Equal(outputPacket.connectTokenData[:connectTokenPrivateBytes-MacBytes], plaintextPrivateVector[:connectTokenPrivateBytes-MacBytes]))
}

func TestWireCompatConnectionDeniedPacket(t *testing.T) {
	vector := loadVector(t, "packet_connection_denied.bin")

	writeWireCompatPacket(t, &connectionDenied{}, 0x11, vector)

	_, ok := readWireCompatPacket(t, vector, 0x11).(*connectionDenied)
	check(t, ok)
}

func TestWireCompatConnectionChallengePacket(t *testing.T) {
	vector := loadVector(t, "packet_connection_challenge.bin")
	encryptedChallengeToken := loadVector(t, "challenge_token_encrypted.bin")

	inputPacket := &connectionChallenge{
		challengeTokenSequence: fixtureChallengeSequence,
		challengeTokenData:     [challengeTokenBytes]byte(encryptedChallengeToken),
	}
	writeWireCompatPacket(t, inputPacket, 0x2233, vector)

	outputPacket, ok := readWireCompatPacket(t, vector, 0x2233).(*connectionChallenge)
	check(t, ok)
	check(t, outputPacket.challengeTokenSequence == fixtureChallengeSequence)
	check(t, bytes.Equal(outputPacket.challengeTokenData[:], encryptedChallengeToken))
}

func TestWireCompatConnectionResponsePacket(t *testing.T) {
	vector := loadVector(t, "packet_connection_response.bin")
	encryptedChallengeToken := loadVector(t, "challenge_token_encrypted.bin")

	inputPacket := &connectionResponse{
		challengeTokenSequence: fixtureChallengeSequence,
		challengeTokenData:     [challengeTokenBytes]byte(encryptedChallengeToken),
	}
	writeWireCompatPacket(t, inputPacket, 0x334455, vector)

	outputPacket, ok := readWireCompatPacket(t, vector, 0x334455).(*connectionResponse)
	check(t, ok)
	check(t, outputPacket.challengeTokenSequence == fixtureChallengeSequence)
	check(t, bytes.Equal(outputPacket.challengeTokenData[:], encryptedChallengeToken))
}

func TestWireCompatConnectionKeepAlivePacket(t *testing.T) {
	vector := loadVector(t, "packet_connection_keep_alive.bin")

	inputPacket := &connectionKeepAlive{clientIndex: 10, maxClients: 16}
	writeWireCompatPacket(t, inputPacket, 0x44556677, vector)

	outputPacket, ok := readWireCompatPacket(t, vector, 0x44556677).(*connectionKeepAlive)
	check(t, ok)
	check(t, outputPacket.clientIndex == 10)
	check(t, outputPacket.maxClients == 16)
}

func TestWireCompatConnectionPayloadPacket(t *testing.T) {
	vector := loadVector(t, "packet_connection_payload.bin")

	payloadData := make([]byte, maxPayloadBytes)
	fixturePattern(payloadData, 23, 11)

	inputPacket := &connectionPayload{payloadData: payloadData}
	writeWireCompatPacket(t, inputPacket, 0x123456789ABCDEF0, vector)

	outputPacket, ok := readWireCompatPacket(t, vector, 0x123456789ABCDEF0).(*connectionPayload)
	check(t, ok)
	check(t, bytes.Equal(outputPacket.payloadData, payloadData))
}

func TestWireCompatConnectionDisconnectPacket(t *testing.T) {
	vector := loadVector(t, "packet_connection_disconnect.bin")

	writeWireCompatPacket(t, &connectionDisconnect{}, 0x556677889900, vector)

	_, ok := readWireCompatPacket(t, vector, 0x556677889900).(*connectionDisconnect)
	check(t, ok)
}
